name: Backend Build
on:
  pull_request:
  push:
    branches: [ master ]
  paths:
    - "server/**" # Only run if only a backend code has changed


backend-build:
    runs-on: ubuntu-latest
    working-directory: ./server
    steps:
      - uses: actions/checkout@v3
        with:
          repository: vitwit/resolute
          path: server
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/**.go
            **/go.mod
            **/go.sum
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: build binary
        run: make build
        if: env.GIT_DIFF
      