name: Deployment

on:
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: echo env
        run: |
          echo ${{secrets.RENDER_SECRET}}
      - name: Deploy
        uses: fjogeleit/http-request-action@v1
        with:
          url: https://api.render.com/deploy/srv-ccadle6n6mponmv5j2ng
          method: GET
          customHeaders: '{"Content-Type": "application/x-www-form-urlencoded"}'
          data: '{"key": ${{secrets.RENDER_SECRET}}}'

