name: Deployment

on:
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: satak/webrequest-action@master
        with:
          url: https://api.render.com/deploy/srv-ccadle6n6mponmv5j2ng?key=${{secrets.RENDER_SECRET}}
          method: GET
