name: Deployment

on:
  push:
    branches: [master]

jobs:
  dev-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: trigger deployment
        run: |
          curl https://api.render.com/deploy/srv-ccadle6n6mponmv5j2ng?key=${{secrets.RENDER_SECRET}}

