name: UI Build and Test
on:
  pull_request:
  push:
    branches: [master]

jobs:
  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: npm ci, build
        working-directory: ./frontend
        run: |
          yarn install --frozen-lockfile
          yarn build
  # frontend-test:
  #   needs: frontend-build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3.5.0
  #     - name: Setup node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 18.x
  #     - name: yarn ci, build and test
  #       working-directory: ./frontend
  #       run: |
  #         yarn install --frozen-lockfile
  #         yarn test
