name: UI Build and Test
on:
  pull_request:
  push:
    branches: [master]

jobs:
  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: npm ci, build
        run: |
          yarn install --frozen-lockfile
          yarn build --if-present
  frontend-test:
    needs: frontend-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: yarn ci, build and test
        working-directory: ./
        run: |
          yarn install --frozen-lockfile
          yarn test
