name: Backend Test
on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  backend-test:
    needs: backend-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: vitwit/resolute
          path: server
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/**.go
            **/go.mod
            **/go.sum
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: run unit tests
        working-directory: ./server
        run: |
          make test
        if: env.GIT_DIFF