name: Test
on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
      - name: yarn ci, build and test
      run: |
        yarn ci
        yarn build --if-present
        yarn test