name: Test
on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  frontend-test:
    needs: frontend-build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
      - name: yarn ci, build and test
      run: |
        yarn ci
        yarn build --if-present
        yarn test
  backend-test:
    needs: backend-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: vitwit/resolute
          path: server
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/**.go
            **/go.mod
            **/go.sum
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: run unit tests
        run: make test
        if: env.GIT_DIFF
      